### ISSUE TITLE
Adicionar requirements.txt ao projeto

### ISSUE THREAD

**Issue by msmagnanijr** [fgsl/podips-writer#7]
Fala Flávio tudo bem? Estou lendo o seu livro e achei bem bacana! Como ponto de melhoria ( boa prática ) poderia adicionar um requirements.txt com as libs utilizadas nesse projeto. Isso irá facilitar a vida do leitor já que para instalar a depêndencias bastaria executar: pip install -r requirements.txt

Abraços

**Comment by fgsl** [comment]
Solved. Thank you for the contribution!

* https://github.com/fgsl/podips-writer/commit/31490b6ca72de5a185b87efbed4ac684b1c02461
* https://github.com/fgsl/podips-writer/commit/8eec809e070e0787c76921100380da5098dd86f8

**Comment by msmagnanijr** [comment]
I'm not sure but I think you forgot to add the "stomp".

**Comment by fgsl** [comment]
> I'm not sure but I think you forgot to add the "stomp".

* https://github.com/fgsl/podips-writer/commit/9449d1c2f44bcb0a3af11d2ae93bb3ed6089a214
* https://github.com/fgsl/podips-writer/commit/3a0e4d00c42d36ac477e417e18cd091040a9dfbc
